import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*
      Dribbble Shot : https://dribbble.com/shots/17011868/attachments/12093006?mode=media
      */}
      <div className='min-h-[100vh] w-[100vw] bg-red-500 bg-[#35373B] text-white'>
          <Header/>
      </div>

    </div>
  )
}
